# Basic
name:               "Johannes Vollmer"
description:        "Coding is like eating lemons, but different"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//johannesvollmer.github.io"
author:             "johannesvollmer"
#twitter:
#  username:         "gfjaru"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "/about"
    
  - name:           "Game of Life"
    href:           "/webgl-of-life"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag