# Basic
name:               "Johannes Vollmer"
description:        "Not yet famous enough for hand-signed distance fields"

url:                "//johannesvollmer.github.io"
author:             "johannesvollmer"

# URL
baseurl:            "" #For Root Domain
#permalink:          /:year/:month/:day/:title/
permalink:          /:year/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "GitHub"
    href:           "https://github.com/johannesvollmer"

  - name:           "ArtStation"
    href:           "https://www.artstation.com/johannesvollmer"

  - name:           "SoundCloud"
    href:           "https://soundcloud.com/johannesvollmer"

  - name:           "LinkedIn"
    href:           "https://www.linkedin.com/in/johannes-vollmer"

# Projects
projects:
    
  - name:           "Regex Nodes"
    href:           "/regex-nodes"
    description:    "A node-based online editor for your regular expressions"
    
  - name:           "WebGL of Life"
    href:           "/webgl-of-life"
    description:    "A price-winning online 'Game of Life' simulation which utilizes the GPU"
    
  # - name:           "JS Sadness"
  #   href:           "https://www.js-sadness.com"
  #   description:    "An online archive of things that make us sad in JavaScript"
    
footer:
  - name: Legal Notice
    href: "/legal-notice"

# Sass
sass:
  sass_dir:         sass
  style:            compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
