# Basic
name:               "Johannes Vollmer"
description:        "Not yet famous enough for hand-signed distance fields"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//johannesvollmer.github.io"
author:             "johannesvollmer"
#twitter:
#  username:         "gfjaru"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            "" #For Root Domain
#permalink:          /:year/:month/:day/:title/
permalink:          /:year/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "Github"
    href:           "https://github.com/johannesvollmer"

  - name:           "Artstation"
    href:           "https://www.artstation.com/johannesvollmer"

  - name:           "Soundcloud"
    href:           "https://soundcloud.com/johannesvollmer"

  - name:           "LinkedIn"
    href:           "https://www.linkedin.com/in/johannes-vollmer"

# Projects
projects:
    
  - name:           "Regex Nodes"
    href:           "/regex-nodes"
    
  - name:           "JS Sadness"
    href:           "www.js-sadness.com"
    
  - name:           "Game of Life"
    href:           "/webgl-of-life"
    
# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
