# Basic
name:               "Johannes Vollmer"
description:        "Not yet famous enough for hand-signed distance fields"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//johannesvollmer.github.io"
author:             "johannesvollmer"
#twitter:
#  username:         "gfjaru"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            "" #For Root Domain
#permalink:          /:year/:month/:day/:title/
permalink:          /:year/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "Github"
    href:           "https://github.com/johannesvollmer"
    external:       true

  - name:           "About"
    href:           "/about"
    external:       false
    
  - name:           "Game of Life"
    href:           "/webgl-of-life"
    external:       true
    
  - name:           "Regex Nodes"
    href:           "/regex-nodes"
    external:       true

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
